#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioFunctions

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "Sounds_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass AudioFunctions.AudioFunctions_C
// 0x0000 (0x0028 - 0x0028)
class UAudioFunctions_C final : public UBlueprintFunctionLibrary
{
public:
	static void PlayRandomSoundAtLocation(ESounds SoundType, const struct FVector& Location, float Pitch_Multiplier, float RandomPitchOffset, float Volume_Multiplier, class USoundAttenuation* AttenuationOverride, class UObject* __WorldContext);
	static void Test(ESounds SoundType, const struct FVector& Location, float Pitch_Multiplier, float RandomPitchOffset, float Volume_Multiplier, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AudioFunctions_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AudioFunctions_C")
	}
	static class UAudioFunctions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioFunctions_C>();
	}
};
DUMPER7_ASSERTS_UAudioFunctions_C;

}

