#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BSideRookChar

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "BP_RookChar_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BSideRookChar.BP_BSideRookChar_C
// 0x0080 (0x0850 - 0x07D0)
class ABP_BSideRookChar_C final : public ABP_RookChar_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_BSideRookChar_C;                 // 0x07D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class USkeletalMeshComponent*                 CannonMesh;                                        // 0x07D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CannonMesh3P;                                      // 0x07E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           ShootRepeater;                                     // 0x07E8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         BurstCount;                                        // 0x07F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentBurstCount;                                 // 0x07F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          cannon;                                            // 0x07F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7F9[0x3];                                      // 0x07F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BuildTimer;                                        // 0x07FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CachedRotation;                                    // 0x0800(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         BuildTimestamp;                                    // 0x080C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LastGroundedTimestamp;                             // 0x0810(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Building;                                          // 0x0814(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ClientClimbing;                                    // 0x0815(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_816[0x2];                                      // 0x0816(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                LastInputVector;                                   // 0x0818(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_824[0x4];                                      // 0x0824(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_BSideWall_C*>                SpawnedWalls;                                      // 0x0828(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         MaxWallCount;                                      // 0x0838(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BuildTime;                                         // 0x083C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumberCannonShots;                                 // 0x0840(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         currentShots;                                      // 0x0844(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BSideRookChar(int32 EntryPoint);
	void ShootDirectionCannonServer();
	void ShootDirectionCannonMulti();
	void ShootDirectionCannon();
	void DestructibleDestroyed(class ABP_Destructible_C* Destructible);
	void CreateBSideWall(const struct FVector& Spawn_Transform_Location, const struct FRotator& Spawn_Transform_Rotation, bool Vertical);
	void SetClientClimbing(bool ClientClimbing_0, const struct FVector& LastInputVector_0);
	void DisableBuilding();
	void ToggleBuilding();
	void DisableCannon();
	void LaunchCannonball();
	void StartCannon();
	void ForceStopScope();
	void CustomEvent_0();
	void StartScoping();
	void ReceiveTick(float DeltaSeconds);
	void ShootDirection(const struct FVector& Direction);
	void MainAbility();
	void MovementAbility();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BSideRookChar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BSideRookChar_C")
	}
	static class ABP_BSideRookChar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BSideRookChar_C>();
	}
};
DUMPER7_ASSERTS_ABP_BSideRookChar_C;

}

