#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CreditsButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Button_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CreditsButton.BP_CreditsButton_C
// 0x0008 (0x0290 - 0x0288)
class ABP_CreditsButton_C final : public ABP_Button_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CreditsButton_C;                 // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_CreditsButton(int32 EntryPoint);
	void ReceiveBeginPlay();
	void AfterClickSequence();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CreditsButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CreditsButton_C")
	}
	static class ABP_CreditsButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CreditsButton_C>();
	}
};
DUMPER7_ASSERTS_ABP_CreditsButton_C;

}

