#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JoinButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"
#include "BP_Button_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JoinButton.BP_JoinButton_C
// 0x0028 (0x02B0 - 0x0288)
class ABP_JoinButton_C final : public ABP_Button_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_JoinButton_C;                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   CushionMesh;                                       // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UTutorialWidget_C*                      FindGameText;                                      // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FBlueprintSessionResult>        Sessions;                                          // 0x02A0(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BP_JoinButton(int32 EntryPoint);
	void Join_Game();
	void Selected(bool isSelected);
	void AfterClickSequence();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_JoinButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_JoinButton_C")
	}
	static class ABP_JoinButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JoinButton_C>();
	}
};
DUMPER7_ASSERTS_ABP_JoinButton_C;

}

