#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TutorialButton

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_TutorialButton.BP_TutorialButton_C.ExecuteUbergraph_BP_TutorialButton
// 0x0008 (0x0008 - 0x0000)
struct BP_TutorialButton_C_ExecuteUbergraph_BP_TutorialButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_isSelected;                           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_TutorialButton_C_ExecuteUbergraph_BP_TutorialButton;

// Function BP_TutorialButton.BP_TutorialButton_C.Selected
// 0x0001 (0x0001 - 0x0000)
struct BP_TutorialButton_C_Selected final
{
public:
	bool                                          isSelected;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_TutorialButton_C_Selected;

}

