#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Highlight

#include "Basic.hpp"

#include "E_PP_HighlightState_structs.hpp"


namespace SDK::Params
{

// Function BPI_Highlight.BPI_Highlight_C.ActivateHighlight
// 0x0001 (0x0001 - 0x0000)
struct BPI_Highlight_C_ActivateHighlight final
{
public:
	E_PP_HighlightState                           HighlightState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_Highlight_C_ActivateHighlight;

// Function BPI_Highlight.BPI_Highlight_C.GetRenderedComponent
// 0x0008 (0x0008 - 0x0000)
struct BPI_Highlight_C_GetRenderedComponent final
{
public:
	class UPrimitiveComponent*                    RenderedComponent;                                 // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_Highlight_C_GetRenderedComponent;

}

