#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BSideRookAnimBP

#include "Basic.hpp"


namespace SDK::Params
{

// Function BSideRookAnimBP.BSideRookAnimBP_C.ExecuteUbergraph_BSideRookAnimBP
// 0x0004 (0x0004 - 0x0000)
struct BSideRookAnimBP_C_ExecuteUbergraph_BSideRookAnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BSideRookAnimBP_C_ExecuteUbergraph_BSideRookAnimBP;

}

