#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CannonCopyPose

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass CannonCopyPose.CannonCopyPose_C
// 0x0220 (0x04E0 - 0x02C0)
class UCannonCopyPose_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x02F8(0x01D8)(ContainsInstancedReference)
	class USkeletalMeshComponent*                 Weapon;                                            // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CannonCopyPose(int32 EntryPoint);
	void BlueprintBeginPlay();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CannonCopyPose_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CannonCopyPose_C")
	}
	static class UCannonCopyPose_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCannonCopyPose_C>();
	}
};
DUMPER7_ASSERTS_UCannonCopyPose_C;

}

