#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EndScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass EndScreen.EndScreen_C
// 0x0048 (0x02A8 - 0x0260)
class UEndScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UImage*                                 Image_64;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUMG_Button_C*                          RematchButton;                                     // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUMG_Button_C*                          UMG_Button;                                        // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             WinnerText;                                        // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class ABP_Player_C* Enemy)> ChallengeEnemy;                        // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class ABP_Player_C*                           Enemy;                                             // 0x0298(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          RequestedRematch;                                  // 0x02A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_EndScreen(int32 EntryPoint);
	void SetTied();
	void BndEvt__EndScreen_UMG_Button_1_K2Node_ComponentBoundEvent_1_ButtonClicked__DelegateSignature();
	void BndEvt__EndScreen_UMG_Button_K2Node_ComponentBoundEvent_0_ButtonClicked__DelegateSignature();
	void SetBlackWins();
	void OnSuccess_15FA9B2F4CA0534DB6F33AA1540EF355();
	void OnFailure_15FA9B2F4CA0534DB6F33AA1540EF355();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EndScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EndScreen_C")
	}
	static class UEndScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEndScreen_C>();
	}
};
DUMPER7_ASSERTS_UEndScreen_C;

}

