#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPSChess

#include "Basic.hpp"


namespace SDK::Params
{

// Function FPSChess.FocusChecker.WindowFocusChange
// 0x0001 (0x0001 - 0x0000)
struct FocusChecker_WindowFocusChange final
{
public:
	bool                                          focused;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FocusChecker_WindowFocusChange;

// Function FPSChess.ReplaySystem.ReplayPlay
// 0x0018 (0x0018 - 0x0000)
struct ReplaySystem_ReplayPlay final
{
public:
	class UGameInstance*                          Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Replayname;                                        // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ReplaySystem_ReplayPlay;

// Function FPSChess.ReplaySystem.ReplayRecord
// 0x0018 (0x0018 - 0x0000)
struct ReplaySystem_ReplayRecord final
{
public:
	class UGameInstance*                          Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Replayname;                                        // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ReplaySystem_ReplayRecord;

// Function FPSChess.ReplaySystem.ReplayStop
// 0x0008 (0x0008 - 0x0000)
struct ReplaySystem_ReplayStop final
{
public:
	class UGameInstance*                          Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ReplaySystem_ReplayStop;

// Function FPSChess.SaveGameFunctions.GetMapNames
// 0x0010 (0x0010 - 0x0000)
struct SaveGameFunctions_GetMapNames final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SaveGameFunctions_GetMapNames;

}

