#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameplaySave

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GameplaySave.GameplaySave_C
// 0x0018 (0x0040 - 0x0028)
class UGameplaySave_C final : public USaveGame
{
public:
	float                                         MouseSensitivity;                                  // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MouseSensitivityPlayer2;                           // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InvertY;                                           // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ScopeSensitivity;                                  // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ChatEnabled;                                       // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GameplaySave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GameplaySave_C")
	}
	static class UGameplaySave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameplaySave_C>();
	}
};
DUMPER7_ASSERTS_UGameplaySave_C;

}

