#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HostGame

#include "Basic.hpp"

#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HostGame.SequenceDirector_C
// 0x0000 (0x0030 - 0x0030)
class USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SequenceDirector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SequenceDirector_C")
	}
	static class USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USequenceDirector_C>();
	}
};
DUMPER7_ASSERTS_USequenceDirector_C;

}

