#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KillcamInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KillcamInterface.KillcamInterface_C
// 0x0000 (0x0000 - 0x0000)
class IKillcamInterface_C final
{
public:
	void InitAsReplayActor();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("KillcamInterface_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KillcamInterface_C")
	}
	static class IKillcamInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IKillcamInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IKillcamInterface_C;

}

