#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KnightAnimBP

#include "Basic.hpp"

#include "PieceAnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass KnightAnimBP.KnightAnimBP_C
// 0x0000 (0x0DB0 - 0x0DB0)
class UKnightAnimBP_C final : public UPieceAnimBP_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("KnightAnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KnightAnimBP_C")
	}
	static class UKnightAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnightAnimBP_C>();
	}
};
DUMPER7_ASSERTS_UKnightAnimBP_C;

}

