#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickControls

#include "Basic.hpp"


namespace SDK::Params
{

// Function PickControls.PickControls_C.ExecuteUbergraph_PickControls
// 0x0010 (0x0010 - 0x0000)
struct PickControls_C_ExecuteUbergraph_PickControls final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameMapsSettings*                      CallFunc_GetGameMapsSettings_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PickControls_C_ExecuteUbergraph_PickControls;

}

