#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShateredScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ShateredScreen.ShateredScreen_C
// 0x0010 (0x0270 - 0x0260)
class UShateredScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UImage*                                 Image_0;                                           // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ShateredScreen(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ShateredScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShateredScreen_C")
	}
	static class UShateredScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShateredScreen_C>();
	}
};
DUMPER7_ASSERTS_UShateredScreen_C;

}

