#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SwordSwingObject

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SwordSwingObject.SwordSwingObject_C
// 0x0020 (0x0240 - 0x0220)
class ASwordSwingObject_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UNiagaraComponent*                      SwordTrailF;                                       // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USplineComponent*                       ForwardSpline;                                     // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SwordSwingObject(int32 EntryPoint);
	void Reverse();
	void BndEvt__SwordSwingObject_SwordTrailF_K2Node_ComponentBoundEvent_0_OnNiagaraSystemFinished__DelegateSignature(class UNiagaraComponent* PSystem);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SwordSwingObject_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SwordSwingObject_C")
	}
	static class ASwordSwingObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASwordSwingObject_C>();
	}
};
DUMPER7_ASSERTS_ASwordSwingObject_C;

}

