#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThreeDMainMenuGameMode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 3DMainMenuGameMode.3DMainMenuGameMode_C
// 0x0010 (0x02D0 - 0x02C0)
class AThreeDMainMenuGameMode_C final : public AGameModeBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_3DMainMenuGameMode(int32 EntryPoint);
	void ReceiveBeginPlay();
	void OnSuccess_C1CA602E44C666B44972B1BC626C4763();
	void OnFailure_C1CA602E44C666B44972B1BC626C4763();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("3DMainMenuGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"3DMainMenuGameMode_C")
	}
	static class AThreeDMainMenuGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AThreeDMainMenuGameMode_C>();
	}
};
DUMPER7_ASSERTS_AThreeDMainMenuGameMode_C;

}

