#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TutorialWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TutorialWidget.TutorialWidget_C
// 0x0018 (0x0278 - 0x0260)
class UTutorialWidget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeAway;                                          // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UTextBlock*                             TutorialText;                                      // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TutorialWidget(int32 EntryPoint);
	void StopFadingAway();
	void StartFadingAway();
	void TutorialWidget_C_3_Event_0(class UTutorialWidget_C* TutorialWidget_C_3);
	void Set_Text(const class FString& Text);
	void Set_Font_Size(int32 In_Font_Info_Size);
	void SequenceEvent__ENTRYPOINTTutorialWidget_0(class UTutorialWidget_C* TutorialWidget_C_3);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TutorialWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TutorialWidget_C")
	}
	static class UTutorialWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTutorialWidget_C>();
	}
};
DUMPER7_ASSERTS_UTutorialWidget_C;

}

