#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_ActionMapper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UMG_ActionMapper.UMG_ActionMapper_C
// 0x00F0 (0x0350 - 0x0260)
class UUMG_ActionMapper_C : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UTextBlock*                             ActionNameText;                                    // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 KeybindImg1;                                       // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInputKeySelector*                      Selector1;                                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UInputKeySelector*                      Selector2;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   ActionName;                                        // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputActionKeyMapping                 CurrentActionKeyMapping;                           // 0x0290(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsAction;                                          // 0x02B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputAxisKeyMapping                   CurrentAxisKeyMapping;                             // 0x02C0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         Original_Scale;                                    // 0x02E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2EC[0x4];                                      // 0x02EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionKeyMapping                 CurrentActionKeyMapping2;                          // 0x02F0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FInputAxisKeyMapping                   CurrentAxisKeyMapping2;                            // 0x0318(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         index1;                                            // 0x0340(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         index2;                                            // 0x0344(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Original_Scale2;                                   // 0x0348(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CollapseOption2;                                   // 0x034C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_UMG_ActionMapper(int32 EntryPoint);
	void BndEvt__UMG_ActionMapper_Selector2_K2Node_ComponentBoundEvent_3_OnIsSelectingKeyChanged__DelegateSignature();
	void BndEvt__UMG_ActionMapper_Selector1_K2Node_ComponentBoundEvent_2_OnIsSelectingKeyChanged__DelegateSignature();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void BndEvt__UMG_ActionMapper_Selector2_K2Node_ComponentBoundEvent_1_OnKeySelected__DelegateSignature(const struct FInputChord& SelectedKey);
	void BndEvt__Selector_K2Node_ComponentBoundEvent_0_OnKeySelected__DelegateSignature(const struct FInputChord& SelectedKey);
	void UppercaseWords(const class FString& In, class FString* Word);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UMG_ActionMapper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UMG_ActionMapper_C")
	}
	static class UUMG_ActionMapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUMG_ActionMapper_C>();
	}
};
DUMPER7_ASSERTS_UUMG_ActionMapper_C;

}

