#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_Lobby

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"
#include "UMG_classes.hpp"
#include "AdvancedSessions_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UMG_Lobby.UMG_Lobby_C
// 0x0068 (0x02C8 - 0x0260)
class UUMG_Lobby_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FindingGameLoop;                                   // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUMG_Button_C*                          BackButton;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCheckBox*                              CheckLAN;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Divider_1;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             FindingGame;                                       // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_91;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUMG_Button_C*                          RefreshButton;                                     // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             SessionContainer;                                  // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUMG_Session_C*                         UMG_Session;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<struct FBlueprintSessionResult>        Sessions;                                          // 0x02B0(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          LAN;                                               // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UMG_Lobby(int32 EntryPoint);
	void BndEvt__UMG_Lobby_CheckLAN_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void BndEvt__UMG_Lobby_RefreshButton_K2Node_ComponentBoundEvent_3_ButtonClicked__DelegateSignature();
	void BndEvt__UMG_Lobby_BackButton_K2Node_ComponentBoundEvent_2_ButtonClicked__DelegateSignature();
	void Refresh();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void FindingGame_Event_3(class UTextBlock* FindingGame_0);
	void FindingGame_Event_2(class UTextBlock* FindingGame_0);
	void FindingGame_Event_1(class UTextBlock* FindingGame_0);
	void FindingGame_Event_0(class UTextBlock* FindingGame_0);
	void OnSuccess_E27F5740418475A43032DABB55C3BE6F(const TArray<struct FBlueprintSessionResult>& Results);
	void OnFailure_E27F5740418475A43032DABB55C3BE6F(const TArray<struct FBlueprintSessionResult>& Results);
	void OnSuccess_1E6DB45B401F29D4D0E0439EDA6433B9(const TArray<struct FBlueprintSessionResult>& Results);
	void OnFailure_1E6DB45B401F29D4D0E0439EDA6433B9(const TArray<struct FBlueprintSessionResult>& Results);
	void AddSessionList(const struct FBlueprintSessionResult& Session, bool LAN_0);
	void SequenceEvent__ENTRYPOINTUMG_Lobby_0(class UTextBlock* FindingGame_0);
	void SequenceEvent__ENTRYPOINTUMG_Lobby_1(class UTextBlock* FindingGame_0);
	void SequenceEvent__ENTRYPOINTUMG_Lobby_2(class UTextBlock* FindingGame_0);
	void SequenceEvent__ENTRYPOINTUMG_Lobby_3(class UTextBlock* FindingGame_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UMG_Lobby_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UMG_Lobby_C")
	}
	static class UUMG_Lobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUMG_Lobby_C>();
	}
};
DUMPER7_ASSERTS_UUMG_Lobby_C;

}

